let authors = new Map();
authors.set('AL', 'Arda Lou');
authors.set('ALL', 'Arda Lou Latham');
authors.set('AEDW', 'Aunt Esther & Debbie Welfle');
authors.set('B', 'Becky');
authors.set('BS', 'Becky Stoll');
authors.set('BI', 'Becky & Rita');
authors.set('NSKS', 'Ben Stoll & Kristen Stoll');
authors.set('T', 'Betty');
authors.set('BM', 'Betty Malone');
authors.set('DW', 'Debbie Welfle');
authors.set('DWKH', 'Debbie Welfle & Karen Houser');
authors.set('D', 'Donna');
authors.set('GS', 'Grandma Stoll');
authors.set('JM', 'Jane Mills');
authors.set('JB', 'Jayne Brunow');
authors.set('J', 'Jesse');
authors.set('JS', 'Julie Stoll');
authors.set('KS', 'Kelly Stoll');
authors.set('Y', 'Larry');
authors.set('LS', 'Lisa Stoll');
authors.set('LT', 'Lucille Trendy');
authors.set('MBL', 'Mabel');
authors.set('M', 'Mariellen');
authors.set('MA', 'Mary Ann');
authors.set('MAS', 'Mary Ann Stoll');
authors.set('MB', 'Mary Bleile');
authors.set('MBDW', 'Mary Bleile & Debbie Welfle');
authors.set('F', 'Mary Frances Stoll');
authors.set('P', 'Pauline');
authors.set('I', 'Rita');
authors.set('IL', 'Rita & Lois');
authors.set('R', 'Robin');
authors.set('TIM', 'Tim Maloney');
authors.set('TM', 'Tina Moore');
authors.set('V', 'Virginia');
authors.set('N', '');

let categories = new Map();
categories.set(0, 'Appetizers');
categories.set(1, 'Breads and Rolls');
categories.set(2, 'Cakes and Cookies');
categories.set(3, 'Candies and Sauces');
categories.set(4, 'Desserts');
categories.set(5, 'Main Dishes');
categories.set(6, 'Soups and Salads');
categories.set(7, 'Vegetables');
categories.set(8, 'Potpourri');
